### PR TITLE
Swift styling cleanup

### PR DESCRIPTION
**Pull request by freak4pc**
Saw your tweet about this project and noticed a few things that are a tad strange compared to the Swift guidelines, so pushed a quick PR :) 

Let me know if you have any questions or thoughts about this 🕺 

🍻

### CODE REVIEW

**Comment by nehayward** [comment]
Wow! Thank you so much I’ll definitely merge this and I’m totally open to more suggestions.

**Comment by freak4pc** [comment]
Feel free to merge at will :)

**Review by nehayward — APPROVED** [review]
Thanks for the feedback! What's a good inter for swift?

**Comment by freak4pc** [comment]
SwiftLint! :-) https://github.com/realm/SwiftLint

**Pull request merged**
